### PR TITLE
Refactor to add 14

### PR DESCRIPTION
**Pull request by szymon-rd**
Attempt to expand the database

### CODE REVIEW

**Comment by szymon-rd** [comment]
@AndrewFeeney I can't get it right, the tests are failing, can you help?

**Comment by szymon-rd** [comment]
It is alternative solution to #28, I think we have to discuss which is better to go forward with (this one has tests failing but I think I can argue that there are some advantages that just need a little bit of work)

**Comment by AndrewFeeney** [comment]
With regret I am unable to merge this PR as another earlier one with a similar feature has just been merged. I can see that you poured a great deal of effort into this, and I appreciate it. If you would like to modify it and reopen it, I would gladly reconsider it.

**Comment by AndrewFeeney** [comment]
If you feel that your implementation offers advantages I'm open to hearing them.

**Pull request closed without merging**
